from typing import Protocol


class Archiver(Protocol):
    def archive(local_path: str, upload_path: str, encryption: bool): ...
    def push_tree(local_path: str, upload_path: str): ...
    def restore(local_path: str, upload_path: str): ...