from typing import Protocol


class Archiver(Protocol):
    def archive(origin_path: str, backup_path: str, encryption: bool): ...
    def push_tree(origin_path: str, backup_path: str): ...
    def restore(origin_path: str, backup_path: str): ...