from typing import Protocol


class Backuper(Protocol):
    def push(local_path: str, sync_path: str, archive_mode: bool, encryption: bool): ...
    def push_tree(local_path: str, sync_path: str): ...
    def pull(local_path: str, sync_path: str): ...