from typing import Protocol


class ProjectVersioner(Protocol):
    def push(local_path: str, upload_path: str, encryption: bool): ...
    def push_tree(local_path: str, upload_path: str): ...
    def pull(local_path: str, upload_path: str): ...